### ISSUE TITLE
Crash on startup - index out of bounds

### ISSUE THREAD

**Issue by tajemniktv** [FreezePhoenix/BetterMod#3]
Hi
I was adding some mods to my modpack but suddenly it started crashing on startup pinpointing to BetterMod. I tried disabling mods I added but oddly that didn't work and requires more debugging and most likely a thanos method but I do not have that time on my hands, so maybe you can read something from these logs? 

https://mclo.gs/BdP5F1s

**Comment by FreezePhoenix** [comment]
@tajemniktv I'm terribly sorry for the late response, it seems like MoreCreativeTabs is causing an issue. I'll look into it.

**Comment by FreezePhoenix** [comment]
@tajemniktv Where did you get this build of MoreCreativeTabs? I can't seem to find files that are referenced in it anywhere.

**Comment by tajemniktv** [comment]
Well, apologies for even later response. I'm not entirely sure where it came from, and most likely won't find out, that's why I'll just close this issue as stale
