### ISSUE TITLE
Crash on startup (Mixin transformation of BetterHopperBlockEntity failed)

### ISSUE THREAD

**Issue by Mr-Squid42** [FreezePhoenix/BetterMod#4]
https://gist.github.com/Mr-Squid42/acab098aeea7eb6bb54f0f077945f7c7

**Comment by FreezePhoenix** [comment]
Thank you for the bug report, I will let you know when I have fixed this.

**Comment by FreezePhoenix** [comment]
@Mr-Squid42 I believe the issue has been resolved in release 1.7.8. Please let me know if this is not the case.

**Comment by Mr-Squid42** [comment]
Yes, thanks

**Comment by tajemniktv** [comment]
Hey, not sure if it's any similiar, or maybe it could be linked to the Meteor Client mod? Not quite sure but it also references mixin with hoppers
https://mclo.gs/YXvT24b

**Comment by FreezePhoenix** [comment]
@tajemniktv That was similar, but it is actually related to #7
