### ISSUE TITLE
Crash on startup with sodium and indium

### ISSUE THREAD

**Issue by Mr-Squid42** [FreezePhoenix/BetterMod#5]
crash on startup:
https://gist.github.com/Mr-Squid42/4ae48204d1148e165c3ad183e5a5e6d4

**Comment by FreezePhoenix** [comment]
I believe I have fixed this, but am currently waiting on actually building the fixed version of the mod, as various pieces of infrastructure required to build the mod are down.

**Comment by Mr-Squid42** [comment]
thanks
