### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Mr-Squid42** [FreezePhoenix/BetterMod#6]
bettermod 1.7.9
sodium 0.5.11
indium 1.0.34

https://gist.github.com/Mr-Squid42/ad43fcc50ede5b361e9012c5ca644453

**Comment by FreezePhoenix** [comment]
Why... this should have been fixed

**Comment by FreezePhoenix** [comment]
My apologies. This is definitively fixed now. I tested it myself, outside of the development environment.

**Comment by Mr-Squid42** [comment]
thanks
